feathery-org/feathery-react

src/Form.jsx

tested manually, event was emitted on skip action

register skip event

---

src/Form.jsx

fixed a bug where we were passing field values for the repeat parameter, which was causing navigation issues on field change.

fix onchange parameter

---

src/Form.jsx

without a default mask, the onAccept function doesn't actually run so user changes can't be saved for that field

fix text field bug

---

src/Form.jsx

the user-provided onSubmit function should only run when we are otherwise about to successfully submit the step. Any validation errors we catch first should prevent the function from running

refactor validation logic

---

src/Form.jsx

After trying to provide an invalid VIN number, the validity of the input never got reset. This meant Upfront forms couldn't submit even if the field value was changed to a valid value.

Fixed carry-over validity bug for Upfront

---

src/Form.jsx
src/components/GooglePlaces.jsx

two bugs
1. when address line 1 is deleted, other google maps field values also have to be cleared. otherwise typing something into address line 1 will immediately rerender the other fields (but we only want that to happen after clicking an autocomplete option)
2. the google maps component second useEffect function wasn't properly refreshing the function when activeStep is changed because it was removed from the dependency array. this meant we weren't able to navigate from full address step back to partial address step back to full

clear gmap fields when address line 1 is deleted

---

src/components/GooglePlaces.jsx

for some addresses in nyc, there's no city, only a sublocality_level_1 like "bronx"

sublocality if city doesn't exist

---

src/Form.jsx

if value of one field triggers an error on another field, that other field must be cleared, not the field that triggered the error. Also clear errors on submit instead of every time a value is changed

handle errors properly

---

src/Form.jsx

We weren't updating the `filePathMap` when the user would reupload

Fixed file path map bug

---

src/elements/__test__/__snapshots__/RichFileUploader.spec.js.snap
src/elements/fields/MultiFileUploader.jsx
src/elements/fields/RichFileUploader.jsx

We weren't correctly tracking the `required` attribute since the input for the file uploaders is hidden. Now they should both show the proper validation errors and stop submission

Fixed required attr on file uploaders

---

src/elements/fields/SignatureField.jsx
src/elements/fields/index.jsx
src/form/Form.jsx
src/utils/formHelperFunctions.js

1) field width should now respect the width in style > layout > width 
2) the onChange function passed to <Form /> now properly fires after the end of stroke in signature field
3) when trying to evaluate the signature field value during onChange, the value now contains a file with the signature image. previously was just ''

fix signature width and onChange

---

src/elements/fields/RadioButtonGroupField.jsx

on firefox, radio buttons only get evaluated together when name attribute is the same

group radio buttons

---

src/elements/fields/index.jsx

- Fix checkboxes not being contained properly within a cell with width "fit"

fix: Contain checkbox when cell width is "fit"

---

src/elements/fields/CheckboxField.jsx
src/elements/fields/CheckboxGroupField.jsx
src/elements/fields/ColorPickerField.jsx
src/elements/fields/DropdownField.jsx
src/elements/fields/FileUploadField.jsx
src/elements/fields/PinInputField.jsx
src/elements/fields/RadioButtonGroupField.jsx
src/elements/fields/TextArea.jsx
src/elements/fields/TextField.jsx
src/form/Form.jsx
src/form/grid/Cell.jsx
src/utils/formHelperFunctions.js

a few fixes:
1. Unify the change and click triggers for fields in a backwards compatible manner. We have no use cases for distinguishing between these two actions
2. For autosubmit behavior, prefer the submit button click trigger if it has a valid nav rule on it. otherwise, make trigger the field change itself

clean up field change logic

---

src/integrations/stytch.js

Don't include query parameters when logging in. They require whitelisting from stytch

don't include query params in login redirect

---

src/form/Form.tsx
src/utils/init.ts

this import was previously needed when the global.d.ts file was in a different location. if it resides in `src/types` the import is not needed

remove global type import that isn't actually needed

---

src/form/grid/index.tsx

If the background style was not set on a group then the selection/deselection style was wrong (#undefined).

Group undefined Style fix (Stripe)

---

src/elements/basic/ButtonElement.tsx
src/elements/fields/TextField.tsx
src/form/Form.tsx
src/form/grid/Cell.tsx
src/index.tsx
src/integrations/firebase.ts
src/utils/__test__/formHelperFunctions.spec.js
src/utils/__test__/logic.spec.ts
src/utils/__test__/validation.spec.ts
src/utils/client.ts
src/utils/formHelperFunctions.ts
src/utils/logic.ts
src/utils/validation.ts

Custom Validations - Part 1 - Supporting all logic comparisons (field type-specific) but the right side only supports literal values. No field to field comparisons yet.
See PRD : https://docs.google.com/document/d/1i1N8rIHYC2whL3MGq-AP9V-_Npmbo53yk0SM90avlqs/edit#
See: https://www.figma.com/file/rnaRNQXZMQTpYHeAACiSJA/Design-Handoff---Archived-8%2F31%2F22?node-id=3648%3A68636
Test Plan:
- Standard validations
- Std validations take priority over custom validations
- Required
- email
- phone
- Test custom validation operators
- Test is_filled, is_empty on each type TextField - > the advanced fields
- Test is_true/false, on checkbox
- Test is_numerical, is_text for textfield/textarea
- Test is_numerical, is_text for other option on checkbox and radio groups
- Test is_numerical, is_text for …

Custom Validations

---

src/utils/__test__/logic.spec.ts
src/utils/logic.ts

This completes custom validations by adding support for field to field comparisons. This means that the right side of rule comparison expression can now have a mix of free-form values and fields.
See:
https://www.figma.com/file/rnaRNQXZMQTpYHeAACiSJA/Design-Handoff---Archived-8%2F31%2F22?node-id=5282%3A97229
- Test Plan:
- Test field to field comparison on field
- Test field to field comparison on button
- Test single valued field comparison with a multi-valued field (checkbox group)
- Test multi-valued field comparison with a multi-valued field (checkbox groups)
- Test single valued field comparison with a multi-valued field in a REPEAT

Custom Validations - field to field comparison support

---

src/form/Form.tsx
src/form/grid/Cell.tsx
src/utils/__test__/formHelperFunctions.spec.js
src/utils/__test__/hideIfs.spec.ts
src/utils/__test__/logic.spec.ts
src/utils/formHelperFunctions.ts
src/utils/hideIfs.ts
src/utils/logic.ts
src/utils/validation.ts

Hide rule and nav rules now support all of the new operators that custom validation supports.
Test Plan
- Hide If
- Test multi valued rule
- Test field-to-field comparison rule
- Test hide rule on repeat that the indexing works as it did before
- Nav
- Test various conditional nav rules
- Do some regression testing on validations including the sdk method validateStep()

Hide/Nav Rule Refactor to use the new custom validation core logic engine

---

src/elements/fields/PaymentMethodField.tsx

Two issues:
1. Custom fonts are not available in the stripe card element and forcing them to load I was unable to get working at all.
2. Some fonts, even when loaded locally (font book) do not work well in the card element.  For example, Open Sans gets cut off.

Fixing stripe element font issue by forcing san-serif always

---

src/Form/index.tsx
src/integrations/__test__/stripe.spec.ts
src/integrations/stripe.ts
src/utils/__test__/client.spec.js
src/utils/client.ts
src/utils/elementActions.ts

This change adds what we need for basic support of plan selectors with these changes:
- Extending the 'collect payment' action to allow the designer to configure in the button/container details panel a set of products and quantities to be purchased.
-  Removing the additional cost and total cost mapping field from the stripe config.
- Removing the legacy “Select Stripe Product” action .
See spec here: https://docs.google.com/document/d/1ADF3b3u-u008Jyhws6g9DT9VEdYzLkQFLNltiLQAhAs/edit#heading=h.o20ci5mc42q5

Stripe Phase 3 - Simplify Select and Purchase with Actions

---

package.json
src/Form/index.tsx
src/auth/LoginForm.tsx
src/auth/internal/AuthIntegrationInterface.ts
yarn.lock

* fixes issue where stytch wasn't redirecting to login step after clicking logout button. due to `setAuthId('')` being called twice, `rerenderAllForms` was being called twice before Form could re-render, so `render` wouldn't actually change and the form wouldn't execute `getNewStep`
* adds session listener for firebase, achieves parity with stytch

improve logout listeners

---

src/utils/__test__/validation.spec.ts
src/utils/hideAndRepeats.ts
src/utils/validation.ts

1. Validation rules and hide rules on a repeating element must be specifically evaluated against sibling repeat elements if they are in the rule.
2. Validation/hide rules on a non-repeating element that involve repeating fields must evaluate against any/all of the repeating field's values.
2 above was not working properly prior to this fix.  I think 1 was working.

Fixes repeat specific validation logic issues

---

src/Form/grid/StyledContainer/styles.ts
src/Form/grid/StyledContainer/utils.ts

- Add `getElementType` to help get the element's type whether the element is from the editor, a servar field or default element

fix: Element type being undefined due to accessing it from the wrong location

---

src/Form/grid/StyledContainer/utils.ts

- Prioritize the servar type over the root `type` within `getElementType`

fix: Fix the order of getElementType

---

src/Form/grid/StyledContainer/hooks.ts
src/Form/grid/StyledContainer/index.tsx

- Add a key to StyledContainer's div that represents the node
- When unmounting the StyledContainer, ensure we unset `width` and `maxWidth` to avoid the previous `width`/`maxWidth` living through the step change on hosted forms

fix: Fix layout looking incorrect after changing steps on hosted forms

---

src/Form/grid/StyledContainer/styles.ts
src/elements/fields/PhoneField/index.tsx

- Fix issue where the `min-width` and `min-height` are not being overrided on mobile viewport when the container is a root-level pixel container
- Fix Fill containers not allowed to fully shrink when there is margin on their children

fix: Fix min dimensions on pixel containers and fill container's width on mobile viewports

---

src/Form/grid/StyledContainer/styles.ts

- Enforce a width of 50px on Fit-width containers that have no children

fix: Fix empty Fit-width containers not being visible

---

src/elements/styles.ts

- Match the read-only font color on MacOS/iOS to the chosen color of the input

fix: Adjust read-only font color to match the chosen color of the input

---

src/elements/fields/DateSelectorField/index.tsx

1. The value for a full date and time should always have timezone: 2002-10-10T12:00:00−05:00 is equivalent to 2002-10-10T17:00:00Z but by convention we should store it in UTC (i.e. with Z).  The date and time is always displayed in the form user's local timezone.  So someone in Chicago would see a time of 12pm for the above example.  When configured as date only, the timezone is still not needed.
2. We should support a 24 hour time picker (00:00 - 23:59).  Seems like this would simply be another checkbox option: '24 hour clock' or something like that.
3. If a value is set using the sdk that is not properly formatted, it should be rejected. Right now it accepts an improperly formatted value and later throws an exception.

Date Selector cleanup and improvements

---

src/Form/grid/StyledContainer/styles.ts

- Fix "Gap" property not applying on containers when set to 0px.

fix: Gap not applying when set to 0

---

src/elements/basic/ButtonElement.tsx

- Ensure line height is `normal` on buttons to ensure 1:1 rendering between dashboard and hosted forms

fix: Bug with line heights on buttons

---

src/utils/__test__/client.spec.js
src/utils/client.ts
src/utils/formHelperFunctions.ts

- Allow lowercase and uppercase HTTP methods in Logic Rules code
- Bump the panel endpoint version to 20 to account for backwards compatibility

refactor: Logic Rule HTTP Changes

---

package.json
src/Form/index.tsx
src/utils/__test__/featheryClient.spec.js
src/utils/featheryClient/index.ts
src/utils/featheryClient/integrationClient.ts
src/utils/offlineRequestHandler.ts

Test plan and observations:
- Go offline right after step 1 loaded, offline throughout last step (step 5), then while getting back online immediately submit (normal and slow 3G) → requests are replayed first for “submit” type (not following step order), then for “reigisterEvent” type (following step order).
- Go offline right after step 1 loaded, fill step 1 - step 4, then close form after submit step 4; reopen the form, step 1-4 fields all replayed in order, but without another refresh, filled fields are shown as empty. After a refresh, step 1-4 fields are filled with prior data.
- Go offline after step 1 loaded, then online shortly before submitting step 2; go offline again after step 3 loaded, then online shortly after submitting step 4 → requests are replayed first for “submit” type …

Updated Request Queue

---

src/Form/grid/Element/index.tsx
src/Form/index.tsx
src/elements/components/Placeholder.tsx
src/elements/fields/AddressLine1.tsx
src/elements/fields/DateSelectorField/index.tsx
src/elements/fields/PasswordField.tsx
src/elements/fields/PhoneField/index.tsx
src/elements/fields/TextArea.tsx
src/elements/fields/TextField/index.tsx
src/utils/api/Field.ts
src/utils/formHelperFunctions.ts

In this PR, I added a repeatable index to all instances of placeholders for dynamic setting with arrays. To do so, I created a new `repeat_placeholders` storage and created a proxy object that would handle `placeholder[repeatableIndex]` functions

Added repeatable placeholder

---

package.json
src/Form/index.tsx
src/auth/LoginForm.tsx
src/integrations/utils.ts
src/utils/featheryClient/index.ts
src/utils/init.ts
src/utils/internalState.ts

As a part of the static embed ID project, this PR adds support for embedding your form via its live slug, passed as `formId`.
[DESIGN DOC](https://docs.google.com/document/d/12zPSUgPpQscbbHnQ0n18qi2cN9RGnK2YfzlCrl2jleQ/edit)
[ASANA](https://app.asana.com/0/home/1207048571643766/1206468676347913)

3) Static Embed Id: Support Embeds via Form ID

---

src/Form/index.tsx

This change makes it so autoValidate is set only if there are errors in the form. This means that if a button submits on a valid form, future errors won't be validated until the next submit event.

only setAutoValidate if form is invalid

---

src/elements/fields/DateSelectorField/index.tsx

The editor dropdown has a default value of '12hr', but the servar property `time_format` defaults to undefined. If the user makes a change, `time_format` is set to either '12hr' or '24hr'.
This change makes the default case have a time mask of 'h:mm aa' to align with the editor UI default.

fix: timeMask not being applied correctly

---

src/Form/grid/Element/index.tsx
src/elements/fields/DateSelectorField/index.tsx

Fixes DateSelector change events from triggering errors while typing a date. Now errors are triggered on calendar select and field blur. This is similar to how phone input works, where errors are suppressed until a valid input is entered.
- Input text is selected on focus
- Calendar opens on focus and prevent errors from autofocusing calendar on mobile
- Datepicker onChange does not trigger errors
- Datepicker onComplete updates value and triggers errors

fix: datepicker input triggering errors

---

src/elements/fields/DateSelectorField/styles.tsx

Style fix so that time picker no longer wraps when the field input width is small. 
Before            | After
:-------------------------:|:-------------------------:
Intended screen size styling is unaffected, so large screen sizes still show calendar and time picker side-by-side and smaller sizes show them stacked.

enforce calendar width

---

src/Form/grid/Element/index.tsx
src/Form/index.tsx

Adds a readonly prop for `<Form>` that allows step navigation but no edits, validation, or submitting.

add readonly prop to form

---

src/elements/fields/PhoneField/index.tsx

The phone field does not accept iOS autofill phone numbers. This is because our input validation prevents inputs that are missing the country code, however iOS autofill replaces the contents and ends up deleting the country code.
At the start of validation we check if the input is a valid phone number that is missing a country code. If so we prepend the country code to it and continue validation.
**Devices:** [MacOS Chrome, Android Chrome, iOS Safari]
**Setup:** Created a basic form with a default phone field. Published the form and opened the test form URL.
**Steps:**
1.  Typing in number without country code works and phone is formatted as the user types
2. Pasting in number without country code works
3. (On iOS) Using keyboard autofill correctly enters the number and formats it …

fix: phone field support iOS autofill

---

src/elements/fields/CheckboxField.tsx
src/elements/fields/CheckboxGroupField.tsx
src/elements/fields/MatrixField.tsx
src/elements/fields/RadioButtonGroupField.tsx
src/utils/browser.ts

This fixes a bug where iOS devices do not scroll to radio buttons or checkboxes on focus. The bug was causing confusion where a user would receive no feedback of missing fields when trying to submit a step.
Added a focus handler for all inputs of type `checkbox` or `radio`. On focus, if the input is not in the viewport and the device is running iOS, we manually scroll to the input. This matches the behavior on desktop and android devices.
**Devices:** [Android - Chrome, Macbook - Chrome, iPhone 9 - Safari]
**Form:** https://form.feathery.io/to/pRq7c7 
A three step form where each step is either a validated radio group, checkbox group, or matrix. The submit button is below and requires scrolling past the input to press.
For each step I scrolled to the bottom and attempted to submit. The …

fix: iOS radio button and checkbox error message

---

src/Form/grid/Element/index.tsx
src/elements/fields/TextField/index.tsx

Fixes a bug where android keyboard would lose their place while typing and cause double letters when using keyboard suggestions.
On embedded forms, the android keyboard was losing track of the current word whenever the first character was typed. This caused it to not fully replace the word when a word suggestion was clicked.
By moving the onChange logic out to the Element instead of inside the TextField we create a workaround for the issue, where rerenders are now triggered properly. Further investigation and fixes need to be made in the future to fix the underlying issue with embedded forms, rerenders, and field state.
1. [Created a form](https://app.feathery.io/forms/ff6300bd-6e29-48ec-825f-b37412ea040b/) which tests each property of a text field. 
2. Completed the form on an embedded …

fix: android keyboard breaking suggestion

---

src/utils/featheryClient/integrationClient.ts
src/utils/offlineRequestHandler.ts

Fixes a bug found by @avnkailash  relating to outdated form versions.
[LOOM](https://www.loom.com/share/c51e5d1951094df0aed3428a7fab34b4?sid=eab62436-16d3-44f1-b486-618dabe2e52c)
When you go to a new step and changes are submitted to `/api/panel/step/submit/v3/`, if the user's form version is not the most recently published version of the form, the backend throws a 409: Conflict error (this is done via the `verify_form_version` decorator on `APIPanelStepSubmitView` [here](https://github.com/feathery-org/feathery-backend/blob/master/apps/api/views.py)).
In the react SDK, the 409 [error is handled](https://github.com/feathery-org/feathery-react/blob/35de89b472bdae806379c6d990d97ee60642645f/src/utils/featheryClient/integrationClient.ts#L29) by calling reload on the window object.
In the …

Fix: outdated form version triggers popup

---

src/Form/grid/Element/index.tsx

Fixes a bug for a customer where a button with an `ACTION_STORE_FIELD` action and `disable_if_fields_incomplete`  property would always be disabled.
Now the disable check will not consider the button itself for checking required fields.

fix: button with set value action cannot disable itself

---

src/elements/fields/SignatureField/components/SignatureCanvas.tsx
src/elements/fields/SignatureField/components/SignatureModal.tsx
src/elements/fields/SignatureField/components/utils.ts
src/utils/browser.ts

Makes various adjustments to the signature field.
- Fixes issue where signature placement would ignore offset and always be positioned in the top left of the canvas.
- Adjusts the signature position to be in the bottom left, to better align with documents
- Trims signature whitespace to allow for better placement and scaling
- Adjusts the scaling of signatures to go up to a maximum of 1.5x scale (previously 1x scale)
| Before | After |
| ------------- | ------------- |
| <img width="413" alt="image" src="https://github.com/feathery-org/feathery-react/assets/29380383/1c065382-7efc-4170-8743-5c978fdd0839">  | <img width="413" alt="image" src="https://github.com/feathery-org/feathery-react/assets/29380383/015516c4-b6b3-4686-b202-c4b534ca0dd1">  |
| <img width="328" alt="image" …

feat: better signature position and scaling

---

src/Form/grid/StyledContainer/styles.ts
src/elements/fields/DropdownMultiField.tsx

Fixes some sizing issues on multi-dropdown fields with long option labels, where the field width would expand and break user experience, especially on mobile devices.
Removes css property `min-width: min-content` on the container around a multi-dropdown. This property didn't work well with the composition of the dropdown component and was causing issues where long labels would force the field to expand horizontally. By removing this property, we allow the the labels to wrap, and keep the field width to its expected size.
Adds extra padding so that the selected options do not expand into the dropdown indicator chevron on the right.
Very long labels can now wrap onto multiple lines in order to fit. There is a maximum of three lines before the remaining content is truncated.

fix: multiselect dropdown expands past max-width

---

src/elements/components/useTextEdit.tsx

Removes the useEffect automatically selecting text on edit mode change. This effect is unnecessary and caused issues with the double click select change on the dashboard.

Double click element to enter text edit

---

src/elements/fields/DateSelectorField/index.tsx
src/elements/fields/DateSelectorField/styles.tsx

Fixes a bug where the datepicker modal (show on touch devices) would be positioned incorrectly. In the picture, note how the overlay for the calendar is offset from the edge, and the calendar is not centered to the screen.
This issue is caused by css behavior where a fixed element is positioned relative to one of its ancestors instead of the viewport, if that ancestor has a transform property. In the example, the containing section had css `transform: translateY(15px)` causing the calendar picker modal to be mispositioned.
To fix this, we use the standard approach of moving the modal to an outside div. In React this is a portal. Instead of placing the modal next to the datepicker field, we are putting it as a direct child of the body. This allows it to act more like a modal, being …

fix: datepicker modal positioning

---

src/Form/grid/Element/index.tsx
src/elements/fields/DateSelectorField/index.tsx

Fixes an issue where date parsing would not work if the user typed their date without slashes. Now the input is masked so all input is properly formatted.
Also fixes an issue where the date might not update if onChange was called before onComplete with the same date while typing. Now the change is only triggered once the date is completely selected and parsed. This ensures that the date value is carried out through the form. It also stops extra onChange events from firing while the user is typing their date.
Testing form: https://form.feathery.io/to/zt3lqY
**Testing:**
- Date formats work with MM/DD/YYYY and DD/MM/YYYY
- Date restrictions work, specific dates, no weekends, past and future only
- Time formats work 12 hour format with AM/PM and 24 hour format
- Time restrictions work, …

fix: date picker typed input

---

src/utils/array.ts

Fixes a bug where values could be set incorrectly in a repeating container.
https://github.com/user-attachments/assets/e264d628-a377-4a13-a413-b4bd207049f2
If there are two fields inside a repeating container with value arrays of different lengths, the longer array determines the number of rows the container is repeated. When attempting to edit a field in the shorter array, the index could go out-of-bounds, and our current logic would insert the new value at the end of the array rather than at the correct index.
This was affecting all field types and causes some strange behavior. In the video, you can see that the wrong checkbox is checked. If you have text fields, each character typed would fill out the next field from the start. So instead of `[null, null, null, 'test']`, you would end …

fix: support repeating values of different lengths

---

src/elements/fields/QRScanner/index.tsx
src/elements/fields/QRScanner/utils/local-storage.ts

Saves the deviceId and current zoom level in local storage.
The next time the scanner is opened on the device (across submissions & sessions) the scanner will attempt to open the previous camera before defaulting to regular camera selection algorithm.

save camera and zoom preferences in local storage

---

src/elements/fields/QRScanner/constants.ts
src/elements/fields/QRScanner/index.tsx
src/elements/fields/QRScanner/utils/local-storage.ts
src/elements/fields/QRScanner/utils/select-camera.ts
src/elements/fields/QRScanner/utils/supports-zoom.ts

Improvements to the QR scanner
- Added property for closing the camera after scanning. If this is missing or false the camera will stay open after a scan allowing the user to keep scanning without reopening the camera.
- Set the aspect ratio of the camera view to `4 / 3`. This makes the component size consistent across devices where previously the height would vary depending on the native camera aspect ratio.
- Replaced the native html zoom slider with a custom one. The native html slider has poor UX on safari. This change makes the slider usable and consistent across devices.
- Removed saving the zoom preference from previous scans. The camera preference is still stored in local storage for use in other sessions and form submissions, but the zoom will now also be reset to default zoom.

qr code improvements

---

src/elements/fields/SignatureField/components/SignatureCanvas.tsx

Checks that the signature file has some data before changing the field value. If the file size is 0, the signature is not saved, the canvas is cleared and an error is logged to console.
Tested the case where signatures are being converted successfully.

Add check for file size in signature field

---

src/Form/grid/Element/index.tsx
src/elements/fields/PinInputField/index.tsx

Fixes an issue where PinInput fields would autofocus on load, even if they were not the first field on a page. The fix was to make the pin field's auto focus conditional based on being the first empty field of a step on a form with autofocus enabled.
**Testing**
- Created a form with 2 steps, one where the pin input is the first field and a second where the pin input is further down the step.
- When the form has autofocus enabled, the step with the pin first will autofocus the pin input, and the other step will autofocus the text field (first field)
- When the form has autofocus disabled, the first field is never automatically focused.
- The pin input still has proper internal focus behavior, where typing in a character will move between input squares, etc.
- The pin input is focused when …

remove forced autofocus on pin input

---

src/elements/fields/index.tsx

Removes extra padding that is applied to phone fields based on the max border size. This makes the phone field consistent in size and behavior with other fields.

fix extra padding from border for phone input

---

src/elements/fields/CheckboxGroupField.tsx
src/elements/fields/RadioButtonGroupField.tsx

Fixed an issue where the labels for radio groups and checkbox groups on repeating fields would be attached to the first group instead of the group it is next to.
Solution:
Make the label a parent of the input instead of siblings. This makes the label automatically link to the input instead of needing a unique id to be linked.
The label also has a `style="display: contents;"` which will ensure the label element will not interfere with dom layout.
| Before  | After |
| ------------- | ------------- |
| <img width="634" alt="image" src="https://github.com/user-attachments/assets/55a9b4bb-178d-44fa-8db2-5bc35558e6be">  | <img width="634" alt="image" src="https://github.com/user-attachments/assets/272fd739-c1cf-4d3f-9e75-782f1867985c">  |
| <img width="510" alt="image" …

fix: corrected labels for repeating checkbox groups and radio groups

---

src/elements/fields/FileUploadField.tsx

Adds file drag and drop handling to the file upload field. 
Minor refactors to share the file upload code between the file input change event and the drop event.
Currently no UI changes for when a file is being dragged on top of the dropzone

feat: Dropzone support for file upload field

---

src/utils/hideAndRepeats.ts
src/utils/repeat.ts

Fixes repeated container logic.
With the old logic, the position [6,10,3] was considered a child of [6,1] because "6,10,3" starts with "6,1".
The new logic does a more robust check, by comparing each element in the parent position.

fix: Correct logic for adding repeating container

---

src/Form/index.tsx

Fixes an issue where the remove repeated container action would remove seemingly random containers.
Add container action has an additional dropdown for selected the repeated container. This selection is saved in the action property `repeat_container`. The Remove container action does not have this configuration in the UI, but the action handler references it when removing the container. 
This causes an issue when a button is switched from the add action (with a container configured) to the remove action. Instead of removing the nearest container, the action will instead remove the container that was configured for the add action.
The fix is to ignore that property for the remove action.

fix: Remove repeated container action removing wrong container

---

src/utils/hideAndRepeats.ts

- before a containers position was not included in the hiddenPositions when validating the step so validation would check fields within the container. This change makes is so that when the container is hidden using styles visibility property the container position is considered hidden when validating the step.

fix: Include position for containers hidden using styles.visibility in hiddenPositions

---

src/elements/fields/PhoneField/index.tsx

Adds support for pasting in full numbers into the phone field. Logic is that if there are multiple pluses in the input, then we only consider the input starting from the last plus symbol.
Typing in a plus on its own still has the expected behavior of opening the country picker.

fix: Phone field paste

---

src/elements/fields/DateSelectorField/index.tsx
src/elements/fields/DateSelectorField/useDateLocale.ts
src/elements/fields/SignatureField/components/SignatureCanvas.tsx
src/elements/fields/SignatureField/components/SignatureModal.tsx
src/elements/fields/SignatureField/index.tsx
src/elements/fields/SignatureField/translation.ts

Adds translation support for Signature and Date Picker fields. The datepicker library uses date-fns and locales to generate the labels, so we create a custom locale integrating the user's translations. The signature translation is much simpler and we just replace the hardcoded text with the translation.
Full form with translation
Signature field
Date field

feat: Translation for signature and date fields

---

src/elements/fields/DateSelectorField/styles.tsx

Increases the selector specificity and adds `!important` to `appearance: none` for the datepicker month and year dropdowns.
Hopefully makes conflicting styles from customers less common.

fix: Add !important and higher css specificity

---

src/Form/index.tsx
src/utils/array.ts
src/utils/formHelperFunctions.ts

Changes the default fill of repeated field arrays from null (which get ignored and indexes change) to "" (which will keep the indexes correct). If a field is passed into the array fill, we use that field's default value.
Testing: 
* Tested Ken's use-case where repeated, optional integer fields weren't submitted correctly and empty fields would be removed. Now the form results correctly show those optional fields as empty.
* Integer fields when submitted with an empty `""` value are maintained in the form results
* Tested Checkbox fields inside repeated containers. These also now correctly reflect their state when submitted.
* Fields inside a repeated container that have a default value also now submit their default value instead of blank if they are submitted.
* Non repeated text and …

fix: Repeated value fill with empty string not null

---

src/utils/featheryClient/index.ts
src/utils/formHelperFunctions.ts

Fixes the issue where the variant form in an ab test would not have it's logic rules.
| Main  | Variant (Note: no console) |
| ------------- | ------------- |
| <img width="554" alt="image" src="https://github.com/user-attachments/assets/fe4da930-75d7-4c45-b021-1f20313b0554" />  | <img width="554" alt="image" src="https://github.com/user-attachments/assets/682df5e0-48c5-499d-a49d-9a214cf6ae8d" />  |
| Main  | Variant |
| ------------- | ------------- |
| <img width="554" alt="image" src="https://github.com/user-attachments/assets/af5d530e-b1f3-4219-8005-8c5d2e8f8020" />  | <img width="554" alt="image" src="https://github.com/user-attachments/assets/17231753-de73-4e41-a463-012e8b11dfe0" />  |

fix: Abtest for logicrules and connectors

---

src/elements/basic/ButtonElement.tsx
src/utils/formHelperFunctions.ts

Changes the button type depending on the button's validate & submit property. If the button does not validate the fields, it is `type="button"`. If it is set the button is `type="submit"`. In order for `type='button'` to have error messages, we render a hidden input for them.
Previously all buttons were of type submit regardless of the property. This was causing issues where the browser automatically presses the submit button after certain actions (eg. iOS Safari paste OTP code). Because every button is a submit button, the browser picks the first one and not necessarily the "validate and submit" button. In the user's case the first button was a resend otp code action, causing the verification for the first code to fail.
| Before  | After |
| ------------- | ------------- |
| <img …

fix: Only submit buttons are type submit

---

src/elements/basic/ButtonElement.tsx
src/utils/formHelperFunctions.ts

Button uuids can start with numbers. Ids in html cannot start with numbers. In order to prevent errors I switched the button error id from `<uuid>_error` to `error_<uuid>`.

fix: Buttons have invalid id sometimes. Fix error Selector

---

src/integrations/recaptcha.ts

Adds a max timeout while waiting for recaptcha. If it fails to load we skip verifying the user and let them through.

fix: Add fallback for recaptcha

---

src/elements/fields/CustomField/template.tsx

Removes url.revokeObjectURL for dynamic imports in custom fields. Revoking the url is unnecessary and potentially causes loading issues if the url is revoked before the module is fully evaluated. 
Awaiting the import resolves before the module is fully evaluated, so there is a race condition with the url revoking and the module full loading.

fix: Custom field race condition

---

src/elements/basic/ButtonElement.tsx
src/elements/components/ErrorInput.tsx
src/elements/fields/ButtonGroupField.tsx
src/elements/fields/QRScanner/index.tsx
src/elements/fields/RatingField.tsx
src/elements/fields/SignatureField/index.tsx

Fixes an issue where clicking the label on a button group would cause its hidden file input to open.
We use a file input to display native HTML errors on elements that do not use input tags. The file input is hidden to prevent the user from interacting with it, its only purpose is to display the real field's error. The issue is that the field's label can open the file input when the label is clicked, since the real field and the file field use the same id.
I fixed the issue by replacing the file input with a text input. This fixed the file picker window from appearing, but reintroduces an issue with virtual keyboards. To fix that issue I set the [inputMode to 'none'](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode#none). I also added some extra fail safes to …

fix: Hidden file input opening

---

src/Form/index.tsx
src/utils/featheryClient/index.ts
src/utils/formContext.ts
src/utils/internalState.ts

Adds support for field set overrides in document extractions.
Previously the function signature was `runAIExtraction(extractionId: string, runAsync: boolean, pages?: number[])`. We would have needed to add overrideId as another optional, unnamed parameter.
Instead, now runAIExtraction accepts an options object as the second parameter, where waitForCompletion, pages, and overrideId can be configured: 
```
runAIExtraction(extractionId: string, options: {
waitForCompletion: boolean; 
pages?: number[]; 
overrideId?: string;
})
```
There is code to support both the original parameters and the new options parameters, depending on if the second parameter is an object.

feat: Support field set extractions

---

src/elements/components/InlineTooltip.tsx
src/elements/components/TextHoverTooltip.tsx
src/elements/fields/AddressLine1.tsx
src/elements/fields/ButtonGroupField.tsx
src/elements/fields/CheckboxGroupField.tsx
src/elements/fields/DateSelectorField/index.tsx
src/elements/fields/DropdownField.tsx
src/elements/fields/DropdownMultiField.tsx
src/elements/fields/MatrixField.tsx
src/elements/fields/PasswordField.tsx
src/elements/fields/PaymentMethodField.tsx
src/elements/fields/PhoneField/index.tsx
src/elements/fields/RadioButtonGroupField.tsx
src/elements/fields/TextArea.tsx
src/elements/fields/TextField/TextAutocomplete.tsx
src/elements/fields/TextField/index.tsx

Fixes rendering issues caused by tooltips and overlays portaling into the document body. Now they portal into the field's container element.
Testing:
- Tested a form on hosted service for no visual changes
- Tested a js embedded form with no z-index issues for no visual changes
- Tested a js embed that renders the form in a sidebar to test portal fix.
- before this change, tooltips, autocomplete suggestions, and dropdowns would not render properly since they render under the sidebar
- with the changes applied the overlays render inside the form and they have proper z-index stacking. 
**Components tested**
* Textfield with autocomplete suggestions
* Textfield with inline tooltip
* Matrix field with tooltip
* Dropdown Multiselect (both the options overlay and options tooltips)
* Datepicker …

fix: Portal issues with tooltips and overlays

---

src/Form/index.tsx
src/elements/fields/PasswordField.tsx

Adds `feathery` class to the feathery form. Increases password input style specificity by scoping it to the feathery class.
This change makes feathery styles have slightly more priority over other CSS on the page. It also gives the feathery form a class that users can target if they wish.
Currently I've only applied this scope to the password input, but we should be able to add to everywhere else in the near future. I'm currently exploring if it's possible to add it globally in emotion, or if we would need to add it to every css prop.

fix: Scope styles to feathery

---

src/elements/fields/CustomField/template.tsx
src/elements/fields/CustomField/useCustomComponentIframe.tsx

Fixes an issue where initial custom props are not rendered in custom field during first render. This was an issue for embedded forms which were not rerendering the custom field on load. I ended up simplifying the custom field rendering to only happen inside of our custom hook. (Before there was an initial render in the iframe, and subsequent renders were in the hook)
Now the initial render, and rerenders caused by value updates are handled the same way and with all props applied.
Testing:
- Tested the custom field loads in both hosted form and embedded js form
- Tested the custom field is rendered with custom props
- Tested the custom field responds to value updates from outside the custom field
- Tested the custom field emits value changes to the form on update

fix: Custom props rendering

---

src/elements/fields/CustomField/template.tsx

Custom field used unpkg for its runtime babel dependency. Switched to jsdelivr cdn for reliability and consistency with our react lib

refactor: Switch babel dependency from unpkg to jsdelivr

---

src/elements/fields/CustomField/index.tsx

Properly re-render custom field when metadata props change.
Now changing the custom props in the editor will change the component in the editor.

fix: Rerender custom field in editor when prop change

---

package.json
src/elements/fields/DateSelectorField/index.tsx
yarn.lock

Changes the imports for Imask.MaskedRange and Imask.MaskedEnum to import directly from imask instead of through imask-react. No functional change but there were issues updating the react lib version for the dashboard because of this.
Tested that datepicker still has a properly masked input (selecting a date formats it correctly, cannot type invalid characters into the input)
Typing a valid date into the input changes the calendar view correctly

fix: Change imask import

---

src/Form/index.tsx

Form component now has `trackHashes` prop. If specified it will be used instead of the form's `track_hashes` setting set in Feathery.
Testing: 
Form uses the setting if no override is set
Passing in `trackHashes={true}` always tracks hashes (even if setting is false)
Passing in `trackHashes={false}` never tracks hashes (even if setting is true)

feat: Add prop to allow overriding track hashes form setting

---

src/elements/fields/CustomField/useCustomComponentIframe.tsx

CustomProps changing was causing full component to refresh instead of just rerendering the component.

fix: CustomProps should not cause reload

---

package.json
src/elements/components/IMaskInput/IMaskInput.tsx
src/elements/components/IMaskInput/index.ts
src/elements/components/IMaskInput/useIMask.ts
src/elements/fields/DateSelectorField/index.tsx
src/elements/fields/TextField/index.tsx
yarn.lock

Replaces the `react-imask` library with our own IMaskInput implementation.
Uses the same underlying `imask` library for masking functionality and logic.
IMaskInput is used for TextFields (custom masks and also password, ssn, etc. inputs), and in the DateSelector element.
The new IMaskInput implements all of the same functionality as the old input as well as maintaining behavior.
**TextField**
* TextField with input restrictions (eg. alphanumeric)
* TextField with custom mask and uses static chars and symbolic chars
* TextField with custom mask, save masked value or unmasked value setting
* Setting TextField value from logic rule
* Setting Masked TextField value from logic rule
**Password field**
* Autocomplete password works
* Hide/show works
**Integer field**
* Mask limits input to …

feat: New IMaskInput component. Remove react-imask dependency

---

src/elements/fields/DateSelectorField/index.tsx
src/elements/fields/TextField/index.tsx
webpack.node.js

Fixes the import issues caused by the imask and react-imask libraries. The fix was to add imask and react-imask into our bundle and change the import to require the cjs version of the package. 
This doesn't downgrade the imask version, so we are still able to make use of the newer imask functionality for our textfield component.
Tested packaged builds of this version on dashboard and hosted-forms apps as npm installs.
Tested built umd version as js embed.
Tested on imask testing form:
- Date picker and text fields work
- Custom masks and input restrictions work
- Setting field value in logic rule properly updates input value
- Default value set in editor is loaded
- Prefill value from url param is set when loading the form.

fix: IMask build and import

---

src/elements/fields/CustomField/template.tsx

Improves the parsing of module imports to handle subpaths. Before, if an import contained a `/` it would not be included in the import map.
Instead of using a complicated regex to match imports, we now manually parse each line.

fix: Handle subpaths during import parse

---

src/Form/index.tsx
src/auth/internal/AuthIntegrationInterface.ts
src/auth/utils.tsx
src/integrations/firebase.ts
src/utils/featheryClient/index.ts

replaces firebase auth redirect flow with popup flow instead. Since popup flow does not trigger a form reload like redirecting does, we need to manually navigate to the login step on auth success.

fix: Firebase auth

---

src/elements/fields/PhoneField/CountryDropdown.tsx

Fixes styling issue with phone dropdown. Sometimes the country flag emojis were rendering with 0 height. This change forces them to be the normal height.

fix: Add line-height to phone country dropdown

---

src/index.tsx

Fixes an issue with the root management logic in `Feathery.renderAt` which was causing the root nodes to be unmounted at the wrong time when `Feathery.renderAt` was called multiple times on the same element. Issue was introduced with the React upgrade changes as React 18 and 19 introduced a new way of rendering React roots.
Now we maintain the list of mounted roots and properly unmount the previous form when rendering a new form at the element.

fix: Fix error when rendering form multiple times

---

src/elements/fields/DateSelectorField/index.tsx

fixes an issue where focus styles were still being applied to date pickers after selecting a date in the calendar.

fix: Unfocus Date Picker on Calendar Select

---

src/elements/basic/ButtonElement.tsx
src/elements/components/TextNodes.tsx
src/elements/components/useTextEdit.tsx

* Text selection area is not expanded on button elements with images
*  This was causing images to be displayed on edge of the button
| Before | After |
| ------ | ------ |
| <img width="425" alt="image" src="https://github.com/user-attachments/assets/5b46f59e-038e-45ec-bc49-2472b1f5ccaf" /> | <img width="425" alt="image" src="https://github.com/user-attachments/assets/97bab374-0800-4285-a35f-8328be32b0ca" /> |
* Rich text content is handled manually instead of using `contentEditable='plaintext-only'`
* There is a bug in React where elements with `contentEditable='plaintext-only'` do not get their `onSelect` callback registered. This was causing the text selection issue where only the full text node could be styled.
* Now we override the `onPaste` event to handle html content
| Before | …

fix: Text selection bug and button image alignment bug

---

src/elements/fields/DropdownMultiField.tsx
src/utils/formHelperFunctions.ts

Fixed handling of option objects in repeated field configurations. Previously, when updating options for a specific repeated field index from a logic rule, we did not support setting options with labels.
Example of logic rule that causes issue:
```js
const data = [
{ value: 'fruit_apple', label: 'Apple', type: 'fruit' },
{ value: 'fruit_banana', label: 'Banana', type: 'fruit' },
{ value: 'fruit_orange', label: 'Orange', type: 'fruit' },
{ value: 'vegetable_cabbage', label: 'Cabbage', type: 'vegetable' },
{ value: 'vegetable_carrot', label: 'Carrot', type: 'vegetable' },
{ value: 'vegetable_zucchini', label: 'Zucchini', type: 'vegetable' }
];
const triggerIndex = feathery.trigger.repeatIndex;
const filterValue = tyler_filter.value[triggerIndex];
const filteredData =
filterValue === 'all' ? …
```

fix: Handle option object type when setting repeated field options

---

src/elements/fields/ButtonGroupField.tsx
src/elements/fields/CheckboxGroupField.tsx
src/elements/fields/DropdownField.tsx
src/elements/fields/DropdownMultiField.tsx
src/elements/fields/RadioButtonGroupField.tsx
src/hooks/useSalesforceSync.ts

Do not load manual options for dynamic options fields

fix: Do not load manual options, turn off fetch in edit mode

---

src/Form/index.tsx
src/types/Form.ts

Add `actionData` to onAction callback context. `actionData` contains the full action metadata, allowing users to use more complex logic in `onAction`. The original `actions` property is unchanged.
Tested using actionData to log the urls that a button opens on click
```tsx
<Form
{...props}
onAction={(context) => {
if (
context &&
context.trigger.type === 'button' &&
context.actionData &&
(context as any).beforeClickActions
) {
const { actionData } = context;
actionData
.filter((item) => item.type === 'url')
.forEach((item) => {
console.log('Redirecting to:', item.url);
});
}
}}
/>
```
- [✔︎] Cleaned up debug prints, comments, and unused code
- [✔︎] Tested end to end

feat: Add full action data to context in onAction callback

---

package.json
src/elements/fields/TextField/index.tsx
src/elements/fields/TextField/tests/EmailField.spec.tsx
src/elements/fields/TextField/tests/IntegerField.spec.tsx
src/elements/fields/TextField/tests/SSNField.spec.tsx
src/elements/fields/TextField/tests/TextAutocomplete.spec.tsx
src/elements/fields/TextField/tests/TextField.spec.tsx
src/elements/fields/TextField/tests/URLField.spec.tsx
src/elements/fields/TextField/tests/test-utils.tsx
src/setupTests.ts
yarn.lock

- Upgrade react testing library
- Add jest-preview
- Create reusable utils for testing field components
- Add tests for:
-    TextField
-    TextAutocomplete
-    EmailField
-    SSNField
-    IntegerField
-    URLField
- Fix bug where maxLength is ignored for URLField and EmailField
Now that unit testing framework is implemented, the rest of the fields and other components can have tests written for them in the future.

test: Add react unit tests

---

src/elements/fields/DropdownMultiField.tsx

- Display the option when there is no label (e.g., in the case of `Bulk edit`). 
https://github.com/user-attachments/assets/a9a4cbb3-ce6b-4061-9ad4-93f0ce028e68

fix: Multi-dropdown label for bulk edit

---

src/Form/hooks.ts
src/Form/index.tsx

- Handle button status until navigating to the new step
https://github.com/user-attachments/assets/dcc11792-c118-43e2-8bc3-3c7e5b7c5b2b
https://github.com/user-attachments/assets/73df7a07-42e3-4b0d-8f2f-aa45c6abe34e

fix: Handle button status until navigating to the new step

---

package.json
src/Form/grid/Element/index.tsx
src/elements/fields/DropdownField.tsx
src/elements/index.tsx
yarn.lock

- Replace the old `react-visibility-sensor` with `react-intersection-observer`
- The old `react-visibility-sensor` is using the deprecated method, and the unpacked and bundle size are bigger than `react-intersection-observer`
- Fix the duplicated dropdown keys
- There is a possibility to have same name options in the dropdown, and it causes the duplicated key issues.
https://github.com/user-attachments/assets/c2548783-7d5e-4f93-988d-76932256301a
https://github.com/user-attachments/assets/4e32db1f-fceb-4440-b0e6-a5ce3c34acda
https://github.com/user-attachments/assets/faf28225-51a4-4ef4-b63d-880ac628acd3
https://github.com/user-attachments/assets/111a3954-24f3-4867-9c00-604f193cddc4

fix: Update react-intersection-observer and Fix Duplicated Dropdown Keys

---

package.json
yarn.lock

Downgrades `react-datepicker` version to `7.6.0`, the last version before `8.0.0`. Versions `8.0.0` and above have an issue where partial dates are not getting parsed. This requires the user to type the entire date, and the calendar will not update as the user types.

fix: Datepicker typing partial dates

---

src/utils/formContext.ts

Quick fix to include the show/hide rule type in the result of getStepProperties. Without it there is no way to tell if the rule will show or hide the element.

fix: Add ruleType to hideRules in getStepProperties result
