src/Form.jsx

upfront needs to be able to set errors during the actual submission logic execution. To be honest, we don't even need an onValidate function since that can be handled in onSubmit.
also supporting async submission function injection since network requests are probably involved
Manual integration testing of setting errors in onSubmit via hosted-flows

add validation logic to submit

---

src/components/GooglePlaces.jsx

otherwise autocomplete doesn't reappear

reinitialize google maps autocomplete if navigating back to same step

---

src/Form.jsx

currently calling setOptions in onLoad triggers an error because activeStep isn't defined on initial load

fix onload bug

---

src/components/GooglePlaces.jsx
src/utils/__test__/client.spec.js
src/utils/__test__/init.spec.js
src/utils/client.js
src/utils/init.js

Allow preloading forms for performance, tracking by cookie so incognito doesn't "save state". fix google maps updating

updates for upfront

---

package.json
src/Form.jsx
src/utils/__test__/client.spec.js
src/utils/client.js
webpack.development.js

https://app.asana.com/0/0/1200363488545472/f

Added next_step_key support to registerEvent

---

src/Form.jsx

Fixing onLoad was pretty straightforward since we don't have a ton of side effects afterwards, however onSubmit was really stuck in its current spot. It should be refactored when we have more time.

Rearranged hooks to behave during async behavior

---

src/Form.jsx

e.g. if user calls setValues multiple times

set field values on load

---

package.json
src/Form.jsx
src/components/GooglePlaces.jsx
src/fields/MultiFileUploader.jsx
src/fields/RichFileUploader.jsx
src/fields/__test__/MultiFileUploader.spec.js
src/fields/__test__/RichFileUploader.spec.js
src/fields/__test__/Text.spec.js
src/fields/__test__/__snapshots__/MultiFileUploader.spec.js.snap
src/fields/__test__/__snapshots__/RichFileUploader.spec.js.snap
src/fields/index.js
src/utils/client.js
src/utils/image.js
yarn.lock

WIP: Still working on PDF thumbnails, but this is fit for review

Enabled support for rich file uploader

---

src/Form.jsx

pass previousStepName for onLoad

---

src/fields/ButtonElement.jsx
src/fields/MultiFileUploader.jsx
src/fields/__test__/MultiFileUploader.spec.js
src/fields/__test__/__snapshots__/MultiFileUploader.spec.js.snap

Fixed two warnings - a memory leak caused by calling `setShowSpinner` after a button was unmounted and an async `setThumbnailsData` called during unit tests.
Also added a test for MultiFileUploader to check for initial files.

Fixed memory leak and testing warning

---

src/Form.jsx

button groups need to register in browser history

fix history navigation

---

src/Form.jsx
src/utils/init.js

so we can let customer pass in their own auth data (from e.g. cookies) and build our auth wall around this information

manage auth id and auth phone number state

---

src/fields/ButtonElement.jsx

useless since font colors are defined on the rich text

remove hover and selected font colors from button

---

src/elements/fields/PinInput.jsx

From thread: https://feathery.slack.com/archives/C02AYGFN03Y/p1631054670004100?thread_ts=1630618279.031800&cid=C02AYGFN03Y

Resolve highlighting last pasted digit

---

src/elements/fields/TextField.jsx
src/form/Form.jsx

otherwise plaid integration might break with hidden field collision

force all text fields to work with strings

---

src/form/Form.jsx
src/utils/formHelperFunctions.js

upfront's request: https://feathery.slack.com/archives/C02AYGFN03Y/p1641355705019800?thread_ts=1641330172.018800&cid=C02AYGFN03Y
tested via hosted-forms and my own onError callback function

on error callback function

---

src/form/Form.jsx
src/utils/formHelperFunctions.js

upfront request: https://feathery.slack.com/archives/C02AYGFN03Y/p1641828835003500

pass trigger info into error callback

---

src/form/Form.jsx
src/utils/client.js

https://sentry.io/organizations/feathery-forms/issues/2945113049/?project=6078176&query=is%3Aunresolved

don't redirect until all requests finish

---

src/elements/fields/DropdownField.jsx
src/elements/fields/TextField.jsx
src/form/Form.jsx
src/utils/client.js
src/utils/init.js

https://sentry.io/organizations/feathery-forms/issues/2941684118/?project=6078176&query=is%3Aunresolved

block on fetch await

---

src/utils/formHelperFunctions.js

https://sentry.io/organizations/feathery-forms/issues/2961352948/?project=6078176&referrer=slack

skip validation if empty and optional

---

src/form/Form.jsx

https://sentry.io/organizations/feathery-forms/issues/2963979791/?project=6078176&referrer=slack

pass clear loader function in

---

src/utils/formHelperFunctions.js

handle repeated values for hidden fields

---

src/form/Form.jsx

breaks if trying to add captch to button that's not rendered

filter rendered buttons for recaptcha

---

src/form/Form.jsx

https://sentry.io/organizations/feathery-forms/issues/3070334950/events/5d4569c65aeb41daa7aca192bd8d3222/?project=6078176&referrer=slack#tags

more graceful error handling

---

package.json
src/elements/index.jsx
src/form/Form.jsx
yarn.lock

Do you think the way we call `fieldOnView` is appropriate? it fires for each field - and it seems each `<VisiblitySensor />` also fires once at the start to report the initial status. should we batch this?

add onView and onViewFields to Form

---

src/integrations/plaid.js

https://sentry.io/organizations/feathery-forms/issues/3337238305/?project=6078176&referrer=slack

no actions if plaid hasn't been loaded

---

src/form/Form.jsx

https://sentry.io/organizations/feathery-forms/issues/3339376513/?project=6078176&referrer=slack

fix firebase undefined bug

---

src/elements/components/useTextEdit.jsx

otherwise weird cursor effects

only editable when element is focused

---

src/elements/styles.js
src/form/grid/index.jsx

- Add support for background images on cells
- Add background image styles to cells

feat: Support background images and styling on cells

---

src/elements/fields/SignatureField.jsx
src/elements/fields/index.jsx

- Ensure height is applied properly to signature elements

fix: Ensure height is applied properly to signature elements

---

.circleci/config.yml
package.json
src/elements/fields/DateSelectorField/dateSelector.css
src/elements/fields/DateSelectorField/index.jsx
src/elements/fields/index.jsx
src/form/grid/Cell.jsx
src/utils/image.js
yarn.lock

i had to regenerate the yarn lock and node_modules files to get the css file import working with webpack

date selector support

---

package.json
src/elements/fields/AddressLine1.jsx
yarn.lock

switch debounce to lodash fn package

---

src/index.tsx
src/integrations/segment.ts
src/integrations/stripe.ts
src/integrations/stytch.ts
src/utils/browser.ts
src/utils/client.ts
src/utils/init.ts

Test Plan
Non-NextJS
- Segment - configure it and run any form
- Stripe - configure it and run stripe payment method form
- Stytch - configure it
- Test cookie
In NextJS
- Segment - configure it and run any form
- Stripe - configure it and run stripe payment method form
- Form with uploaded font 
- Test fingerprint and cookie
- Test UpdateUserKey
- NextJS linked to reathery-react - do a build

Document abstraction - improve NextJS support

---

src/utils/client.ts

https://sentry.io/organizations/feathery-forms/issues/3777604186/?project=6078176&referrer=slack#exception

catch json parse errors and re-emit with more info

---

src/elements/fields/PinInputField.tsx

creates helper function so rawValue is set correctly in all locations
also fixes the check in handleMultipleValues that would only evaluate the first item in the array

fix PIN raw value

---

src/Form/index.tsx
src/integrations/__test__/stripe.spec.ts
src/integrations/stripe.ts
src/integrations/utils.ts
src/utils/__test__/client.spec.js
src/utils/client.ts
src/utils/elementActions.ts
src/utils/formHelperFunctions.ts

See: https://docs.google.com/document/d/1KI1sSi54yGQKMVj7PBgDz0v-gy7M-qVSdYQbZdecI1s/edit# for details.

Stripe Phase 2 - collect payment action and stripe checkout support

---

src/Form/components/grid/index.tsx
src/Form/index.tsx
src/utils/hydration.ts

- Change the form to not be a flex-box
- Prevent the grid from being `fill-content` when the axis is fill

fix: Fix step styles not applying

---

src/Form/components/grid/index.tsx

- Prevent CellContainer from rendering anything if the cell is an element and should be hidden

fix: Fix conditionally hidden fields still rendering empty divs

---

src/Form/components/grid/index.tsx

- Apply min-height instead of height on the root node if the height is fill

fix: Overflow styles

---

src/elements/fields/PaymentMethodField.tsx
src/integrations/__test__/stripe.spec.ts
src/integrations/stripe.ts

Thought I/we tested this originally, but apparently not.  Needed for the ox.work plan selector demo.

Stripe fix: hidden field were not working as product qty fields for purchases

---

src/elements/components/TextNodes.tsx

Steps:
1. Select a non-asset text.
2. Save as asset.
3. At any point later, try and delete the asset.  Boom!

Fixed delete text asset bug

---

src/Form/index.tsx
src/auth/LoginForm.tsx

https://codedamn.com/news/reactjs/how-to-force-render-and-re-render-your-react-components

Fixed issue with container selection state not working reliably with multiple store actions

---

src/Form/index.tsx
src/utils/formHelperFunctions.ts

toggle works with all types as well

fix casting of value for store field action

---

src/Form/index.tsx
src/elements/fields/PhoneField/CountryDropdown.tsx
src/elements/fields/PhoneField/index.tsx
src/utils/validation.ts

removes ambiguity of whether the user needs to type it or not. also removes restriction where user can't type a number that starts with the digit of the country code (there are some countries where that is valid)

put country code into field input

---

src/Form/grid/StyledContainer/hooks.ts
src/Form/grid/StyledContainer/utils.ts

- Add additional checks around the usage of parentNode to ensure the reference exists before using it

fix: parentNode of null issue

---

src/Form/grid/StyledContainer/styles.ts

fix: Checkbox width

---

src/Form/grid/StyledContainer/utils.ts

- Disregard hidden elements from the calculations for the width of Fit containers

fix: Disregard hidden elements from the calculations for the width of Fit containers

---

src/Form/index.tsx

This reverts commit fe0ad29aeee32dfde1715fc8c1332f7ebbdb6611.

Revert "Changes to support await at the top level of user code (#942)"

---

src/Form/index.tsx

Work-around to js eval issue for running rules that caused a bad publish of the lib

---

src/Form/grid/StyledContainer/hooks.ts
src/Form/grid/StyledContainer/utils.ts
src/elements/basic/ImageElement.tsx

- Allow images to with pixel dimensions (width or height) to be responsive in a way that they will shrink if there is not enough room

fix: Allow images with pixel dimensions to be responsive

---

src/Form/grid/StyledContainer/styles.ts

- Remove legacy style rule for containers

fix: Remove legacy rule preventing desktop from being responsive

---

src/Form/grid/StyledContainer/hooks.ts

- Fix miscalculating widths on fit elements due to the calculation for the width running prior to fonts finished loading

fix: Miscalculated width on fit elements

---

src/Form/grid/Element/index.tsx
src/Form/grid/Element/utils.ts

- Fix an issue where whitelisted fields are disabled for collaborators with proper permissions

fix: Fix whitelisting of fields on collaborators

---

src/Form/index.tsx
src/utils/client.ts
src/utils/formHelperFunctions.ts

- Add `connectToAPI` method on `feathery.http` to utilize new API Connectors built by the no-code rule builder

feat: Add API Connector utilities

---

src/elements/fields/SignatureField/components/SignatureModal.tsx
src/elements/fields/SignatureField/index.tsx

- Force signature font to web font "Great Vibes"

fix: Fix Comic Sans appearing as signature font on Windows

---

src/Form/grid/StyledContainer/styles.ts

- Fix empty containers with a pixel height expanding past the specified pixel height

fix: Empty container pixel heights expanding

---

src/Form/grid/Element/index.tsx

- Debounce the onChange method within the form on specific types of elements

feat: Debounce the onChange method within the Form

---

src/Form/components/DevNavBar.tsx
src/Form/grid/StyledContainer/hooks.ts
src/Form/grid/StyledContainer/hooks/index.ts
src/Form/grid/StyledContainer/hooks/useFixedContainer.ts
src/Form/grid/StyledContainer/index.tsx
src/Form/grid/StyledContainer/styles.ts
src/Form/index.tsx
src/elements/components/InlineTooltip.tsx
src/elements/components/LoaderContainer.tsx
src/elements/components/TextHoverTooltip.tsx
src/elements/components/Watermark.tsx
src/elements/fields/ButtonGroupField.tsx
src/elements/fields/ColorPickerField.tsx
src/elements/fields/FileUploadField.tsx
src/elements/fields/PasswordField.tsx
src/elements/fields/RatingField.tsx
src/elements/fields/SignatureField/components/SignatureModal.tsx
src/elements/fields/SignatureField/index.tsx
src/elements/fields/TextField/TextAutocomplete.tsx
src/elements/fields/TextField/index.tsx
src/elements/styles.ts
src/utils/styles.ts

- Add the ability to fix containers (allowing sticky headers and footers)

feat: Fixed containers

---

src/Form/grid/StyledContainer/hooks/useFixedContainer.ts

- Fix containers on the editor reflecting the "Fixed" positioning

fix: Fixed containers on the editor

---

src/elements/fields/SignatureField/components/SignatureCanvas.tsx

- Add 5px of padding to the left side of the signature canvas

fix: Padding on signature element

---

src/elements/fields/SignatureField/components/SignatureModal.tsx

- Fix the Signature Element hanging on "Generating signature..." when removing the text from the input

fix: Signature generation hanging when empty text

---

src/Form/index.tsx
src/utils/client.ts

- Update the AI Extraction action

feat: Update AI Extraction action

---

src/utils/featheryClient/index.ts

- Add a polling mechanism to AI Extraction to avoid timeouts and lower server load

feat: Add a polling mechanism to AI Extractions

---

src/elements/components/useBorder.tsx
src/elements/fields/DateSelectorField/index.tsx
src/elements/fields/DateSelectorField/styles.tsx
src/utils/browser.ts

Improves the datepicker component, especially for mobile devices.
- Adds Month and Year dropdowns for quick date navigation
- Clicking the datepicker on a mobile device opens a modal for choosing the date
- Improves styles for the time picker on mobile devices

Improve date picker for mobile

---

src/elements/fields/SignatureField/components/SignatureModal.tsx
src/elements/fields/SignatureField/index.tsx

update signature font to "La Belle Aurore"

---

package.json
src/Form/index.tsx
src/utils/elementActions.ts
src/utils/featheryClient/integrationClient.ts
src/utils/sensitiveActions.ts

Adds support for verifying phone numbers via SMS using Telesign. We already support voice verification, this extends the integration to include sms.

3) Telesign SMS Verification: SDK

---

src/Form/grid/Container/index.tsx

- Fix unwanted width transitions on containers with actions set on them.

fix: Width transitioning on containers with actions

---

src/elements/fields/PinInputField/index.tsx

Removes some testing styles that slipped through

fix styles

---

src/elements/fields/QRScanner/index.tsx
src/elements/fields/QRScanner/utils/select-camera.ts

Better default camera
Ability to change cameras
Remove image upload

Qr improvements

---

src/utils/featheryClient/integrationClient.ts

- update the payload for generateEnvelopes request to reflect the Quik Forms integration changes on the backend

feat: update generateEnvelopes payload

---

src/utils/formContext.ts
src/utils/internalState.ts

- Fix not being able to pass `pages` to AI Extractions from logic rules

fix: Not able to pass page limiting from logic rules to AI Extractions

---

.github/workflows/release.yml

- Only bump the patch version upon releasing

chore: Update releases to only patch the version

---

src/utils/hideAndRepeats.ts
src/utils/repeat.ts

Fixes the remaining repeated logic issues. This time the rendering logic was invalid. I also checked for any other places where we are handling repeated values for logic issues.

fix: Repeat container render logic

---

src/Form/grid/Element/index.tsx
src/elements/fields/CustomField/Status.tsx
src/elements/fields/CustomField/index.tsx
src/elements/fields/CustomField/template.tsx
src/elements/fields/CustomField/useCustomComponentIframe.tsx
src/elements/fields/index.tsx

Adds initial support for CustomField element, which allows users to write their own React components for their Feathery forms.
Main PR: https://github.com/feathery-org/feathery-frontend/pull/2385

feat: CustomField Element

---

package.json
src/Form/grid/Element/utils.ts
src/elements/fields/TextField/index.tsx
src/utils/validation.ts
yarn.lock

Changes the SSN input mask depending on the last_four_digit servar property.
Normal SSN
Last 4 Digit SSN

feat: Last 4 digits option for ssn field

---

src/elements/components/InlineTooltip.tsx
src/elements/components/Placeholder.tsx
src/elements/fields/AddressLine1.tsx
src/elements/fields/DateSelectorField/index.tsx
src/elements/fields/DateSelectorField/styles.tsx
src/elements/fields/DropdownField.tsx
src/elements/fields/DropdownMultiField.tsx
src/elements/fields/PasswordField.tsx
src/elements/fields/PhoneField/index.tsx
src/elements/fields/SliderField/index.tsx
src/elements/fields/TextArea.tsx
src/elements/fields/TextField/index.tsx
src/elements/fields/index.tsx

Adds RTL support for various elements that were missing support.
| Feature | LTR (regression test) | Old RTL | New RTL |
| --- | --- | --- | --- |
| Field Tooltip | <img width="433" alt="image" src="https://github.com/user-attachments/assets/6d642593-eb82-4247-a4fe-dc0a6bf86c5f" /> | <img width="433" alt="image" src="https://github.com/user-attachments/assets/c92911fe-e45b-41ea-87a1-6167c82545d7" /> | <img width="433" alt="image" src="https://github.com/user-attachments/assets/822c878a-3741-48cf-a564-a78fbff0b045" /> |
| Multiselect Dropdown | <img width="433" alt="image" src="https://github.com/user-attachments/assets/a5ba21b2-542c-44e8-8c14-33a4627ed1a7" /> | <img width="433" alt="image" src="https://github.com/user-attachments/assets/eaf61274-6228-468c-be57-29e92d42ee4e" /> | <img …

feat: Enhanced rtl support

---

src/elements/fields/FileUploadField.tsx

Adds filetype validation to uploaded files. Previously we only had a filetype suggestion used in the finder. This suggestion could be bypassed by selecting 'All files' option in the finder window.
Now on upload we validate the filetype and display an error if it fails validation.

fix: FileUploadField filetype validation

---

src/Form/grid/Element/index.tsx
src/elements/fields/CustomField/index.tsx
src/elements/fields/CustomField/useCustomComponentIframe.tsx

Syncs some form properties and custom properties to custom field components.

feat: Handle Custom field props

---

src/Form/grid/StyledContainer/hooks/index.ts

Fixes theme step background colors not displaying in the editor

fix: Handle step background color in editor

---

src/elements/fields/PhoneField/index.tsx

Adds extra maxLength validation for India phone numbers

fix: India phone validation

---

src/integrations/firebase.ts

Refactor the firebase auth check on load to handle existing sessions. Now, if the user is already signed in, they do not need in after the form loads. Potential fix for the firebase randomly logging out

feat: Recover firebase session on form load

---

src/auth/internal/AuthIntegrationInterface.ts
src/integrations/firebase.ts

Removes the idle logout from auth forms

feat: Handle idle Firebase session

---

src/integrations/persona.ts

Updating persona field values passed back from polling endpoint

feat: Save persona field values to frontend

---

src/utils/browser.ts

Set cookie across entire domain so user IDs aren't path specific

feat: Set user id across entire domain

---

src/elements/fields/ButtonGroupField.tsx
src/elements/fields/CheckboxGroupField.tsx
src/elements/fields/DropdownField.tsx
src/elements/fields/DropdownMultiField.tsx
src/elements/fields/RadioButtonGroupField.tsx
src/hooks/useSalesforceSync.ts
src/utils/featheryClient/integrationClient.ts

Adding the ability for Dropdown and MultiDropdown components to fetch dynamic field values from Salesforce.

feat: Add dropdown sync feature

---

src/Form/index.tsx
src/utils/featheryClient/integrationClient.ts
src/utils/formContext.ts
src/utils/internalState.ts

Allow getting quik forms by dealer natively

feat: Get Quik dealer forms

---

src/utils/featheryClient/integrationClient.ts
src/utils/formContext.ts
src/utils/internalState.ts

- Fixed LoanPro logic rule function names

fix: LoanPro function name fix

---

src/Form/index.tsx
src/utils/error.ts
src/utils/featheryClient/index.ts

Bubble AI extraction errors via logic rule and button action

fix: Show ai extraction errors on form

---

src/Form/index.tsx
src/utils/__test__/featheryClient.spec.js
src/utils/featheryClient/index.ts
src/utils/featheryClient/integrationClient.ts
src/utils/featheryClient/utils.ts
src/utils/offlineRequestHandler.ts

* Failed requests are now retried, even if the user was always online.
* Requests are retried with exponential backoff.
* Failed requests are never dropped.
* If a request fails the retry after 5 attempts we show an alert to the user, warning them that their results aren't being saved. (The user can either refresh or continue with this submission)
* The form completion event is blocked until all pending/failed requests are successful.
* Once the user is back online/requests are succeeding, the user is able to try submitting their step/form again and all step data will be submitted (in the correct order).
* Set up a multi step form with field and file uploads
* All scenarios tested on `hosted-forms` and with a html page with js embedded …

fix: Step submission

---

src/Form/index.tsx
src/Form/tests/index.spec.tsx

- The recent fix for the button action issue has been repeatedly causing new issues.
- It seems that the button related issue needs to be resolved through a different approach.
- To maintain service stability, the recent changes will be reverted and the related tests will be skipped as well until a new solution is implemented.
- https://github.com/feathery-org/feathery-react/pull/1440
- https://github.com/feathery-org/feathery-react/pull/1442
- https://github.com/feathery-org/feathery-react/pull/1443
- https://github.com/feathery-org/feathery-react/pull/1444

fix: Revert Recent Changes That Fixed Button Related Issue

---

src/Form/index.tsx

fix: Safely check shared codes in case backend returns undefined

---

src/Form/definitions.ts
src/Form/logic.ts
src/Form/tests/index.spec.tsx

- Support async functions in Shared Code
- Add unit tests for Shared Codes
https://github.com/user-attachments/assets/8247f08e-94fa-4c49-98a3-340085faa030

fix: Support Async Functions in Shared Code and Add Unit Test

---

package.json
src/elements/fields/QRScanner/index.tsx
src/elements/fields/SliderField/index.tsx
yarn.lock

chore: Upgrade Slider lib version, React 19 support

---

src/elements/fields/FileUploadField.tsx
src/utils/image.tsx

- Update to use `File` type instead of any Promise
- Add an error handler to the file reading function
- Remove the unnecessary async calls 
https://github.com/user-attachments/assets/96a682cb-273a-4a3b-9f30-93b6f037f618

fix: File Upload Issues
